name: $(BuildID)

trigger:
  - 'dev'

pool: TGE # Directement sur la même ligne lorsque pool privée

jobs:
  - job: DscBuild
    strategy:
      parallel: 1
    workspace:
      clean: all
    steps:
      - powershell: '.\Build.ps1 -ResolveDependancy'
        workingDirectory: DSC
        displayName: 'Execution de Build.ps1'

      - task: PublishTestResults@2
        displayName: "Affichage des résultats des tests d'intégration"
        inputs:
          testResultsFormat: NUnit
          testResultsFiles: '**/IntegrationTestResults.xml'
          failTaskOnFailedTests: true

      - task: PublishBuildArtifacts@1
        displayName: MOF
        inputs:
          PathtoPublish: '$(Build.SourcesDirectory)\DSC\BuildOutput\MOF'
          ArtifactName: MOF

      - task: PublishBuildArtifacts@1
        displayName: 'Meta MOF'
        inputs:
          PathtoPublish: '$(Build.SourcesDirectory)\DSC\BuildOutput\MetaMOF'
          ArtifactName: 'Meta MOF'

      - task: PublishBuildArtifacts@1
        displayName: RSOP
        inputs:
          PathtoPublish: '$(Build.SourcesDirectory)\DSC\BuildOutput\RSOP'
          ArtifactName: RSOP

      - task: PublishBuildArtifacts@1
        condition: and(succeeded(), not(startsWith(variables['BHCommitMessage'], '--Added new node')))
        displayName: 'Compressed Modules'
        inputs:
          PathtoPublish: '$(Build.SourcesDirectory)\DSC\BuildOutput\CompressedModules'
          ArtifactName: 'Compressed Modules'

      - task: PublishTestResults@2
        displayName: 'Publish Build Acceptance Test Results'
        inputs:
          testResultsFormat: NUnit
          testResultsFiles: '**/BuildAcceptanceTestResults.xml'
          failTaskOnFailedTests: true
